# Generated by Django 2.2.1 on 2019-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='section',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='section',
            name='work_date',
        ),
        migrations.AddField(
            model_name='section',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='shift',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
