# Generated by Django 2.2.1 on 2019-05-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190519_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventDaySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('eventday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EventDay')),
                ('related_users', models.ManyToManyField(to='polls.PollUser')),
            ],
        ),
    ]
