# Generated by Django 2.2.1 on 2019-05-20 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_eventday_eventdaysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='USR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='day',
        ),
        migrations.RemoveField(
            model_name='section',
            name='related_users',
        ),
        migrations.RemoveField(
            model_name='section',
            name='shift',
        ),
        migrations.AddField(
            model_name='section',
            name='eventday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.EventDay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='EventDaySection',
        ),
        migrations.AddField(
            model_name='usr',
            name='eventdaysection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Section'),
        ),
        migrations.AddField(
            model_name='usr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
