# Generated by Django 2.2.1 on 2019-05-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190520_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usr',
            old_name='eventdaysection',
            new_name='section',
        ),
    ]
