# Generated by Django 2.2.1 on 2019-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190520_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='day',
            field=models.IntegerField(),
        ),
    ]
